# Generated by Django 3.2.18 on 2023-04-16 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookclub', '0002_bookpoll'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='slug',
            field=models.SlugField(default='', max_length=250, unique=True),
        ),
    ]
