# Generated by Django 3.2.18 on 2023-04-16 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookclub', '0004_alter_book_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookpoll',
            options={'ordering': ['start_date']},
        ),
        migrations.AddField(
            model_name='bookpoll',
            name='name',
            field=models.CharField(default='Blank', max_length=75),
        ),
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.CharField(default='Blank', max_length=75),
        ),
    ]
