# Generated by Django 3.2.18 on 2023-05-13 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookclub', '0005_auto_20230512_1522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='votes',
        ),
        migrations.AddField(
            model_name='book',
            name='question',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='bookclub.question'),
        ),
    ]
