# Generated by Django 3.2.18 on 2023-05-13 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookclub', '0006_auto_20230513_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='book',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='bookclub.book'),
        ),
    ]
