# Generated by Django 3.2.18 on 2023-04-30 11:12

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bookclub', '0006_auto_20230425_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=('title',), unique=True),
        ),
    ]
