# Generated by Django 3.2.18 on 2023-05-13 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookclub', '0007_vote_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='question',
        ),
    ]
