# Generated by Django 3.2.18 on 2023-05-13 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookclub', '0008_remove_book_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='book',
        ),
        migrations.AddField(
            model_name='choice',
            name='book',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='bookclub.book'),
        ),
    ]
