# Generated by Django 3.2.18 on 2023-05-07 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookclub', '0008_alter_book_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='created_by',
            field=models.CharField(default='admin', max_length=250),
        ),
    ]
