# Generated by Django 3.2.18 on 2023-05-13 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookclub', '0009_auto_20230513_1532'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='choice_text',
        ),
    ]
