# Generated by Django 3.2.18 on 2023-05-13 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookclub', '0010_remove_choice_choice_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chosen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookclub.vote')),
            ],
        ),
    ]
