# Generated by Django 3.2.18 on 2023-05-11 16:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookclub', '0010_alter_book_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice_Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poll_choice_text', models.CharField(default='empty', max_length=200)),
                ('votes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Question_Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poll_question_text', models.CharField(max_length=200)),
                ('poll_pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        
        migrations.AddField(
            model_name='choice_poll',
            name='poll_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookclub.question_poll'),
        ),
    ]
