# Generated by Django 3.2.18 on 2023-05-07 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookclub', '0011_auto_20230507_1109'),
    ]

    operations = [
        migrations.CreateModel(
            name='PollVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('choices', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote', to='bookclub.book')),
                ('poll', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vote', to='bookclub.bookpoll')),
            ],
        ),
    ]
