# Generated by Django 3.2.18 on 2023-05-09 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookclub', '0011_auto_20230508_1705'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='choice_text',
        ),
        migrations.AddField(
            model_name='choice',
            name='choice_text',
            field=models.ManyToManyField(related_name='poll', to='bookclub.Book'),
        ),
    ]
