# Generated by Django 3.2.18 on 2023-05-11 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookclub', '0011_auto_20230511_1651'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice_poll',
            old_name='votes',
            new_name='poll_votes',
        ),
    ]
