# Generated by Django 3.2.18 on 2023-05-07 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookclub', '0012_pollvote'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookQuestionPoll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poll_title', models.CharField(default='Blank', max_length=75)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
            ],
            options={
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='PollChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choices', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookclub.bookquestionpoll')),
            ],
        ),
        migrations.RemoveField(
            model_name='pollvote',
            name='choices',
        ),
        migrations.RemoveField(
            model_name='pollvote',
            name='poll',
        ),
        migrations.DeleteModel(
            name='BookPoll',
        ),
        migrations.DeleteModel(
            name='PollVote',
        ),
    ]
