# Generated by Django 3.2.18 on 2023-05-09 14:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookclub', '0012_auto_20230509_0803'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='votes',
            field=models.ManyToManyField(blank=True, related_name='votes', to=settings.AUTH_USER_MODEL),
        ),
    ]
