# Generated by Django 3.2.18 on 2023-05-11 17:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookclub', '0012_rename_votes_choice_poll_poll_votes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Choice_Poll',
            new_name='Choice',
        ),
        migrations.AddField(
            model_name='book',
            name='votes',
            field=models.ManyToManyField(blank=True, related_name='votes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='BookPoll',
        ),
    ]
