# Generated by Django 3.2.18 on 2023-05-11 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookclub', '0013_book_votes'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='choice_text',
            field=models.CharField(default='empty', max_length=200),
        ),
    ]
